### ISSUE TITLE
Months

### ISSUE THREAD

**Issue by panther99** [gcwelborn/horoscope#1]
This is just advice - in _horoscope.js_ file you should return error when non-existing month is added :) Although it's easy to add it, it should be there by default - never trust user input!

**Comment by cruzw** [comment]
thanks for the tip!

im adding to the end of top-level if/else statement: 
else { throw new Error("month isn't between 1-12");  }

should I also refine the bottom-level if/else statements that check the day to include 1 at the lower end of the day range? i.e. if (day <= 20 && day > 0) { return "Capricorn"; }

**Comment by panther99** [comment]
> should I also refine the bottom-level if/else statements that check the day to include 1 at the lower end > of the day range? i.e. if (day <= 20 && day > 0) { return "Capricorn"; }

Yes, because someone can add for example -1 or that sort of thing.
